# Generated by Django 4.1.2 on 2022-12-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_access_hash_room_access_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='tags',
            new_name='properties',
        ),
    ]
